### ISSUE TITLE
Issue in launching oke-airflow resouces 

### ISSUE THREAD

**Issue by bharathsajjala** [oracle-quickstart/oke-airflow#2]
**Error: Output refers to sensitive values
  on outputs.tf line 3:
   3: output "SSH_PRIVATE_KEY"" { value = var.use_remote_exec ? tls_private_key.oke_ssh_key.private_key_pem : ""SSH Key provided by user" }**

looks like terraform version needs to be updated

**Comment by smithzc** [comment]
This should be resolved, SSH key output is now wrapped in function to allow it to be displayed in terraform 1.x.
